// Package blog provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package blog

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	OIDCScopes   oIDCContextKey   = "OIDC.Scopes"
	Oauth2Scopes oauth2ContextKey = "Oauth2.Scopes"
)

// Defines values for OrderQuery.
const (
	OrderQueryAsc  OrderQuery = "asc"
	OrderQueryDesc OrderQuery = "desc"
)

// Valid indicates whether the value is a known member of the OrderQuery enum.
func (e OrderQuery) Valid() bool {
	switch e {
	case OrderQueryAsc:
		return true
	case OrderQueryDesc:
		return true
	default:
		return false
	}
}

// Defines values for SearchPostsParamsOrder.
const (
	SearchPostsParamsOrderAsc  SearchPostsParamsOrder = "asc"
	SearchPostsParamsOrderDesc SearchPostsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the SearchPostsParamsOrder enum.
func (e SearchPostsParamsOrder) Valid() bool {
	switch e {
	case SearchPostsParamsOrderAsc:
		return true
	case SearchPostsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Comment defines model for Comment.
type Comment struct {
	// AuthorId User ID from Authentik (need to change subject mode to User's ID instead of hashed)
	AuthorId        Id                  `json:"authorId"`
	Content         string              `json:"content"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	ParentCommentId *openapi_types.UUID `json:"parentCommentId,omitempty"`
	PostId          *openapi_types.UUID `json:"postId,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Message Human-readable error message
	Message string `json:"message"`

	// MoreInfo URL with more information about the error
	MoreInfo *string `json:"more_info,omitempty"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// HasNext Whether there is a next page
	HasNext bool `json:"hasNext"`

	// HasPrev Whether there is a previous page
	HasPrev bool `json:"hasPrev"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Page Current page number
	Page int `json:"page"`

	// Total Total number of items
	Total int `json:"total"`

	// TotalPages Total number of pages
	TotalPages int `json:"totalPages"`
}

// Post defines model for Post.
type Post struct {
	// AuthorId User ID from Authentik (need to change subject mode to User's ID instead of hashed)
	AuthorId     Id                  `json:"authorId"`
	CommentCount *int                `json:"commentCount,omitempty"`
	Content      string              `json:"content"`
	CreatedAt    *time.Time          `json:"createdAt,omitempty"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	Tags         []string            `json:"tags"`
	Title        string              `json:"title"`
}

// Id User ID from Authentik (need to change subject mode to User's ID instead of hashed)
type Id = string

// CommentIdPath defines model for commentIdPath.
type CommentIdPath = openapi_types.UUID

// LimitQuery defines model for limitQuery.
type LimitQuery = int

// OrderQuery defines model for orderQuery.
type OrderQuery string

// PageQuery defines model for pageQuery.
type PageQuery = int

// PostIdPath defines model for postIdPath.
type PostIdPath = openapi_types.UUID

// BadRequestError defines model for BadRequestError.
type BadRequestError = Error

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFoundError defines model for NotFoundError.
type NotFoundError = Error

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = map[string]interface{}

// oIDCContextKey is the context key for OIDC security scheme
type oIDCContextKey string

// oauth2ContextKey is the context key for Oauth2 security scheme
type oauth2ContextKey string

// SearchPostsParams defines parameters for SearchPosts.
type SearchPostsParams struct {
	// Q Full-text keyword for post search
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Tag Filter posts by tag
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`

	// Page Page number for pagination
	Page *PageQuery `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`

	// Order Sort order
	Order *SearchPostsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// SearchPostsParamsOrder defines parameters for SearchPosts.
type SearchPostsParamsOrder string

// UpdatePostJSONBody defines parameters for UpdatePost.
type UpdatePostJSONBody struct {
	Content string   `json:"content"`
	Tags    []string `json:"tags"`
	Title   string   `json:"title"`
}

// UpdateCommentJSONRequestBody defines body for UpdateComment for application/json ContentType.
type UpdateCommentJSONRequestBody = Comment

// ReplyCommentJSONRequestBody defines body for ReplyComment for application/json ContentType.
type ReplyCommentJSONRequestBody = Comment

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody = Post

// UpdatePostJSONRequestBody defines body for UpdatePost for application/json ContentType.
type UpdatePostJSONRequestBody UpdatePostJSONBody

// CommentOnPostJSONRequestBody defines body for CommentOnPost for application/json ContentType.
type CommentOnPostJSONRequestBody = Comment
