---
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: '2'

linters:
  enable:
    - exhaustive
    - exhaustruct
    - sloglint
    - testifylint
    - unparam
  disable:
    - unused
  exclusions:
    generated: strict
  settings:
    exhaustruct:
      allow-empty: false
      allow-empty-returns: false
      allow-empty-declarations: true
      include:
        - github\.com/egolia-uit/egolia/.*\.*
      exclude:
        - github\.com/egolia-uit/egolia/.*/errs\.Err
    sloglint:
      static-msg: true
      no-mixed-args: true
      attr-only: true
      args-on-sep-lines: true
      context: scope

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/egolia-uit
  exclusions:
    generated: strict

run:
  build-tags:
    - integration
