#:schema https://raw.githubusercontent.com/jdx/mise/refs/heads/main/schema/mise.json

[tools]
"go:github.com/goforj/wire/cmd/wire" = "v1.2.0"
"go:github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen" = "2.7.0"
buf = "1.65.0"
"npm:@kevinnitro/nx-cache-action" = "0.1.0"
mockery = "3.7.0"
gotestsum = "1.13.0"
"go:github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter" = "0.1.0"
protoc-gen-go = "1.36.11"
protoc-gen-go-grpc = "1.6.2"
"pipx:codecov-cli" = "11.2.8"
uv = "0.11.17"
python = "3.13.12"

[settings]
legacy_version_file = false
