#:schema https://raw.githubusercontent.com/jdx/mise/refs/heads/main/schema/mise.json

[env]
REDOCLY_TELEMETRY = "off"
REDOCLY_SUPPRESS_UPDATE_NOTICE = "true"
NEXT_TELEMETRY_DISABLED = "1"
'_'.path.paths = ["./scripts/"]

[tools]
"go:github.com/goforj/wire/cmd/wire" = "v1.2.0"
"go:github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen" = "2.7.0"
buf = "1.65.0"
pnpm = "10.28.2"
"npm:skills" = "latest"
mockery = "3.7.0"
yt-dlp = { version = "2026.03.17", rename_exe = "yt-dlp" }
"github:rustfs/cli" = "0.1.13"

[tools.ffmpeg]
version = "latest"
os = ["linux", "darwin"]

[shell_alias]
c = "docker compose"
nx = "pnpm nx"
