#:schema https://raw.githubusercontent.com/jdx/mise/refs/heads/main/schema/mise.json

[env]
REDOCLY_TELEMETRY = "off"
REDOCLY_SUPPRESS_UPDATE_NOTICE = "true"
NEXT_TELEMETRY_DISABLED = "1"

[tools]
"go:github.com/goforj/wire/cmd/wire" = "v1.1.0"
"go:github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen" = "2.6.0"
buf = "1.68.4"
pnpm = "10.28.2"
golangci-lint = "2.11.4"
"npm:skills" = "latest"

[shell_alias]
compose = "docker compose"
nx = "pnpm nx"
