direction: right

vars: {
  d2-config: {
    layout-engine: elk
    theme-overrides: {
      N1: "#4c4f69"
      N2: "#5c5f77"
      N4: "#acb0be"
      N5: "#ccd0da"
      N7: "#eff1f5"
      B1: "#4c4f69"
      B2: "#6c6f85"
      B3: "#bcc0cc"
      B4: "#ccd0da"
      B5: "#dce0e8"
      B6: "#eff1f5"
      AA4: "#1e66f5"
      AA5: "#7287fd"
      AB4: "#8839ef"
      AB5: "#dc8a78"
    }
  }
}

classes: {
  notUsed: {
    style: {
      opacity: 0.4
      stroke-dash: 5
      fill: "#9ca0b0"
      stroke: "#4c4f69"
    }
  }
}

user: User {
  browser: Browser {
    icon: https://cdn.simpleicons.org/googlechrome/e64553
  }
}

istio_system: Istio System {
  ingress: Ingress {
    icon: https://cdn.simpleicons.org/istio/04a5e5
  }
  waypoint: Waypoint {
    icon: https://cdn.simpleicons.org/istio/04a5e5
  }
  ztunnel: ZTunnel {
    icon: https://cdn.simpleicons.org/istio/04a5e5
  }
}

web: Web {
  web: Web {
    icon: https://cdn.simpleicons.org/nextdotjs/4c4f69
  }
}

course: Course {
  course: course {
    icon: https://cdn.simpleicons.org/go/04a5e5
  }
  database: Database {
    icon: https://cdn.simpleicons.org/postgresql/7287fd
  }
  course -> database
}

billing: Billing {
  billing: Billing {
    icon: https://cdn.simpleicons.org/go/04a5e5
  }
  database: Database {
    icon: https://cdn.simpleicons.org/postgresql/7287fd
  }
  billing -> database
}

blog: Blog {
  blog: Blog {
    icon: https://cdn.simpleicons.org/go/04a5e5
  }
  database: Database {
    icon: https://cdn.simpleicons.org/postgresql/7287fd
  }
  blog -> database
}

authentik: Authentik {
  authentik: Authentik {
    icon: https://cdn.simpleicons.org/authentik/fe640b
  }
  database: Database {
    icon: https://cdn.simpleicons.org/postgresql/7287fd
  }
  authentik -> database
}

rustfs: RustFS {
  rustfs: RustFS {
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/rustfs.svg
  }
}

monotoring: Monitoring {
  alloy: Alloy {
    icon: https://raw.githubusercontent.com/grafana/alloy/refs/heads/main/docs/sources/assets/alloy_icon_orange.svg
  }
  prometheus: Prometheus {
    icon: https://raw.githubusercontent.com/prometheus/prometheus/refs/heads/main/documentation/images/prometheus-logo.svg
  }
  loki: Loki {
    icon: https://raw.githubusercontent.com/grafana/grafana/refs/heads/main/public/app/plugins/datasource/loki/img/loki_icon.svg
  }
  tempo: Tempo {
    icon: https://raw.githubusercontent.com/grafana/grafana/refs/heads/main/public/app/plugins/datasource/tempo/img/tempo_logo.svg
  }
  grafana: Grafana {
    icon: https://raw.githubusercontent.com/grafana/grafana/refs/heads/main/public/img/grafana_icon.svg
  }
  alloy -> prometheus
  alloy -> loki
  alloy -> tempo
  prometheus <- grafana
  loki <- grafana
  tempo <- grafana
}

user.browser -> istio_system

istio_system -> web
istio_system -> course
istio_system -> billing
istio_system -> blog
istio_system -> authentik
istio_system -> rustfs
istio_system -> monotoring

billing -> authentik
blog -> authentik

course -> rustfs
blog -> rustfs

style.border-radius: 15
*.style.border-radius: 15
*.*.style.border-radius: 15
*.*.*.style.border-radius: 15
