template: testify
dir: '{{ .InterfaceDir }}'
filename: mock.go
pkgname: '{{ .SrcPackageName }}'
packages:
  github.com/egolia-uit/egolia/internal/blog/domain:
    config:
      include-interface-regex: '^(.*Repo|UnitOfWork|RepoRegistry)$'
