sonar.projectKey=egolia-uit_course
sonar.organization=egolia-uit
sonar.go.activate=true
sonar.dre.go.activate=true
sonar.go.exclusions**/vendor/**, **/testdata/**, **/pkg/pb/**, **/pkg/api/**
sonar.project.monorepo.enabled=true
