// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/egolia-uit/egolia/internal/course"
	"github.com/goforj/wire"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*course.Server, func(), error) {
	server := course.NewServer()
	return server, func() {
	}, nil
}

// wire.go:

var ProviderSet = wire.NewSet(course.ProviderSet, wire.Value(ServiceName), wire.Value(ServiceVersion))
