// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/egolia-uit/egolia/internal/course"
	"github.com/egolia-uit/egolia/internal/course/app"
	"github.com/egolia-uit/egolia/internal/course/component"
	"github.com/egolia-uit/egolia/internal/course/config"
	"github.com/egolia-uit/egolia/internal/course/controller/grpc"
	"github.com/egolia-uit/egolia/internal/course/controller/health"
	"github.com/egolia-uit/egolia/internal/course/controller/http"
	"github.com/egolia-uit/egolia/internal/course/domain"
	"github.com/egolia-uit/egolia/internal/course/infra/objectstorage"
	"github.com/egolia-uit/egolia/internal/course/infra/persistence"
	"github.com/egolia-uit/egolia/internal/course/infra/persistence/readmodel"
	"github.com/egolia-uit/egolia/internal/course/infra/persistence/repo"
	"github.com/egolia-uit/egolia/pkg/common/http"
	"github.com/egolia-uit/egolia/pkg/logging"
	"github.com/egolia-uit/egolia/pkg/otel"
	"github.com/goforj/wire"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*course.Server, func(), error) {
	validate := component.ProvideValidate()
	viper := config.NewViper()
	configConfig, err := config.New(validate, viper)
	if err != nil {
		return nil, nil, err
	}
	log := &configConfig.Log
	stdoutHandler := logging.NewStdoutHandler(log)
	serviceName := _wireServiceNameValue
	serviceVersion := _wireServiceVersionValue
	resource, err := otel.NewResource(ctx, serviceName, serviceVersion)
	if err != nil {
		return nil, nil, err
	}
	loggerProvider, cleanup, err := otel.NewLoggerProvider(ctx, resource)
	if err != nil {
		return nil, nil, err
	}
	slogHandler := otel.NewSlogHandler(serviceName, loggerProvider)
	logger := logging.NewSlog(stdoutHandler, slogHandler, log)
	ginSlogHandlerFunc := commonhttp.NewGinSlogHandler(log, logger)
	otelGinHandlerFunc := commonhttp.NewOtelGinHandler(serviceName)
	general := &configConfig.General
	engine := commonhttp.NewGin(ginSlogHandlerFunc, otelGinHandlerFunc, general)
	tracerProvider, cleanup2, err := otel.NewTracerProvider(ctx, resource)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	handlerProvider := app.NewHandlerProvider(tracerProvider, logger)
	db, cleanup3, err := persistence.NewDB(ctx, configConfig, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	unitOfWork := repo.NewUnitOfWork(db)
	approveCourseHandler := app.NewApproveCourseHandler(unitOfWork)
	bookmarkCourseHandler := app.NewBookmarkCourseHandler(unitOfWork)
	commentOnLessonHandler := app.NewCommentOnLessonHandler(unitOfWork)
	createCourseHandler := app.NewCreateCourseHandler(unitOfWork)
	createDraftVersionHandler := app.NewCreateDraftVersionHandler(unitOfWork)
	createLessonCmd := app.NewCreateLessonCmd(unitOfWork)
	createSectionHandler := app.NewCreateSectionHandler(unitOfWork)
	declineCourseHandler := app.NewDeclineCourseHandler(unitOfWork)
	deleteCourseSvc := domain.NewDeleteCourseSvc()
	deleteCourseHandler := app.NewDeleteCourseHandler(deleteCourseSvc, unitOfWork)
	deleteLessonHandler := app.NewDeleteLessonHandler(unitOfWork)
	deleteLessonCommentHandler := app.NewDeleteLessonCommentHandler(unitOfWork)
	courseRepo := repo.NewCourseRepo(db)
	enrollmentRepo := repo.NewEnrollmentRepo(db)
	reviewRepo := repo.NewReviewRepo(db)
	reviewPolicySvc := domain.NewReviewPolicySvc(courseRepo, enrollmentRepo, reviewRepo)
	deleteReviewHandler := app.NewDeleteReviewHandler(reviewPolicySvc, unitOfWork)
	deleteSectionHandler := app.NewDeleteSectionHandler(unitOfWork)
	editTestLessonHandler := app.NewEditTestLessonHandler(unitOfWork)
	editVideoLessonHandler := app.NewEditVideoLessonHandler(unitOfWork)
	enrollInCourseSvc := domain.NewEnrollInCourseSvc()
	enrollInCourseHandler := app.NewEnrollInCourseHandler(enrollInCourseSvc, unitOfWork)
	finishCourseSvc := domain.NewFinishCourseSvc()
	finishCourseHandler := app.NewFinishCourseHandler(finishCourseSvc, unitOfWork)
	getCourseProgressHandler := app.NewGetCourseProgressHandler(unitOfWork)
	authorizationSvc := domain.NewAuthorizationSvc(courseRepo, enrollmentRepo)
<<<<<<< HEAD
	hideCourseCmd := app.NewHideCourseHandler(authorizationSvc, unitOfWork, logger, tracer)
	createSectionCmd := app.NewCreateSectionHandler(unitOfWork, logger, tracer)
	updateSectionTitleCmd := app.NewUpdateSectionTitleHandler(unitOfWork, logger, tracer)
	deleteSectionCmd := app.NewDeleteSectionHandler(unitOfWork, logger, tracer)
	moveSectionCmd := app.NewMoveSectionHandler(logger, tracer, unitOfWork)
	updateReviewCmd := app.NewUpdateReviewHandler(reviewPolicySvc, unitOfWork, logger, tracer)
	deleteReviewCmd := app.NewDeleteReviewHandler(reviewPolicySvc, unitOfWork, logger, tracer)
	submitCourseCmd := app.NewSubmitCourseHandler(unitOfWork, logger, tracer)
	createDraftVersionCmd := app.NewCreateDraftVersionHandler(unitOfWork, logger, tracer)
	createLessonCmd := app.NewCreateLessonCmd(unitOfWork, logger, tracer)
	editVideoLessonCmd := app.NewEditVideoLessonHandler(unitOfWork, logger, tracer)
	approveCourseCmd := app.NewApproveCourseHandler(unitOfWork, logger, tracer)
	replyOnLessonCommentCmd := app.NewReplyOnLessonCommentHandler(unitOfWork, logger, tracer)
	commentOnLessonCmd := app.NewCommentOnLessonHandler(unitOfWork, logger, tracer)
	editTestLessonCmd := app.NewEditTestLessonHandler(unitOfWork, logger, tracer)
	deleteLessonCommentCmd := app.NewDeleteLessonCommentHandler(unitOfWork, logger, tracer)
	declineCourseCmd := app.NewDeclineCourseHandler(unitOfWork, logger, tracer)
	markLessonAsCompletedCmd := app.NewMarkLessonAsCompletedHandler(unitOfWork, logger, tracer)
	saveVideoLessonProgressCmd := app.NewSaveVideoLessonProgressHandler(unitOfWork, markLessonAsCompletedCmd, logger, tracer)
	resetLessonProgressCmd := app.NewResetLessonProgressHandler(unitOfWork, logger, tracer)
	cmds := &app.Cmds{
		CreateCourse:            createCourseCmd,
		DeleteCourse:            deleteCourseCmd,
		EnrollInCourse:          enrollInCourseCmd,
		FinishCourse:            finishCourseCmd,
		MoveLesson:              moveLessonCmd,
		ReviewCourse:            reviewCourseCmd,
		UpdateCourse:            updateCourseCmd,
		BookmarkCourse:          bookmarkCourseCmd,
		HideCourse:              hideCourseCmd,
		CreateSection:           createSectionCmd,
		UpdateSectionTitle:      updateSectionTitleCmd,
		DeleteSection:           deleteSectionCmd,
		MoveSection:             moveSectionCmd,
		UpdateReview:            updateReviewCmd,
		DeleteReview:            deleteReviewCmd,
		SubmitCourse:            submitCourseCmd,
		CreateDraftVersion:      createDraftVersionCmd,
		CreateLesson:            createLessonCmd,
		EditVideoLesson:         editVideoLessonCmd,
		ApproveCourse:           approveCourseCmd,
		ReplyOnLessonComment:    replyOnLessonCommentCmd,
		CommentOnLesson:         commentOnLessonCmd,
		EditTestLesson:          editTestLessonCmd,
		DeleteLessonComment:     deleteLessonCommentCmd,
		DeclineCourse:           declineCourseCmd,
		SaveVideoLessonProgress: saveVideoLessonProgressCmd,
		MarkLessonAsCompleted:   markLessonAsCompletedCmd,
		ResetLessonProgress:     resetLessonProgressCmd,
	}
=======
	hideCourseHandler := app.NewHideCourseHandler(authorizationSvc, unitOfWork)
	markLessonAsCompletedHandler := app.NewMarkLessonAsCompletedHandler(unitOfWork)
	moveLessonHandler := app.NewMoveLessonHandler(unitOfWork)
	moveSectionHandler := app.NewMoveSectionHandler(unitOfWork)
	replyOnLessonCommentHandler := app.NewReplyOnLessonCommentHandler(unitOfWork)
	reviewCourseHandler := app.NewReviewCourseHandler(reviewPolicySvc, unitOfWork)
	submitCourseHandler := app.NewSubmitCourseHandler(unitOfWork)
	updateCourseHandler := app.NewUpdateCourseHandler(unitOfWork)
	updateReviewHandler := app.NewUpdateReviewHandler(reviewPolicySvc, unitOfWork)
	updateSectionTitleHandler := app.NewUpdateSectionTitleHandler(unitOfWork)
	cmds := app.NewCmds(handlerProvider, unitOfWork, approveCourseHandler, bookmarkCourseHandler, commentOnLessonHandler, createCourseHandler, createDraftVersionHandler, createLessonCmd, createSectionHandler, declineCourseHandler, deleteCourseHandler, deleteLessonHandler, deleteLessonCommentHandler, deleteReviewHandler, deleteSectionHandler, editTestLessonHandler, editVideoLessonHandler, enrollInCourseHandler, finishCourseHandler, getCourseProgressHandler, hideCourseHandler, markLessonAsCompletedHandler, moveLessonHandler, moveSectionHandler, replyOnLessonCommentHandler, reviewCourseHandler, submitCourseHandler, updateCourseHandler, updateReviewHandler, updateSectionTitleHandler)
>>>>>>> origin
	s3 := &configConfig.S3
	objectstorageS3, err := objectstorage.NewS3(ctx, s3)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	courseReadRepo := readmodel.NewCourseReadRepo(db, objectstorageS3)
	getCourseHandler := app.NewGetCourseHandler(courseReadRepo)
	getCourseDetailHandler := app.NewGetCourseDetailHandler(courseReadRepo, authorizationSvc)
	getCourseForUpdateHandler := app.NewGetCourseForUpdateHandler(unitOfWork, courseReadRepo)
	getCourseLandingPageHandler := app.NewGetCourseLandingPageHandler(courseReadRepo)
	reviewReadRepo := readmodel.NewReviewReadRepo(db)
	getCourseReviewsHandler := app.NewGetCourseReviewsHandler(reviewReadRepo)
	lessonCommentReadRepo := readmodel.NewLessonCommentReadRepo(db)
<<<<<<< HEAD
	getLessonCommentsQuery := app.NewGetLessonCommentsHandler(lessonCommentReadRepo, logger, tracer)
	lessonProgressReadRepo := readmodel.NewLessonProgressReadRepo(db)
	getLessonProgressQuery := app.NewGetLessonProgressHandler(lessonProgressReadRepo, logger, tracer)
	queries := &app.Queries{
		GetCourse:               getCourseQuery,
		GetCourseDetail:         getCourseDetailQuery,
		GetMyCourses:            getMyCoursesQuery,
		GetPublishedCourses:     getPublishedCoursesQuery,
		GetLessonDetail:         getLessonDetailQuery,
		GetUploadVideoLessonURL: getUploadVideoLessonURLQuery,
		GetSystemCourses:        getSystemCoursesQuery,
		GetMyBookmarkedCourses:  getMyBookmarkedCoursesQuery,
		GetMyEnrolledCourses:    getMyEnrolledCoursesQuery,
		GetCourseLandingPage:    getCourseLandingPageQuery,
		GetCourseForUpdate:      getCourseForUpdateQuery,
		GetCourseReviews:        getCourseReviewsQuery,
		GetMyCertificates:       getMyCertificatesQuery,
		GetLessonComments:       getLessonCommentsQuery,
		GetLessonProgress:       getLessonProgressQuery,
	}
=======
	getLessonCommentsHandler := app.NewGetLessonCommentsHandler(lessonCommentReadRepo)
	lessonReadRepo := readmodel.NewLessonReadRepo(db, objectstorageS3)
	getLessonDetailHandler := app.NewGetLessonDetailHandler(lessonReadRepo)
	getLessonProgressHandler := app.NewGetLessonProgressHandler(unitOfWork)
	getMyBookmarkedCoursesHandler := app.NewGetMyBookmarkedCoursesHandler(courseReadRepo)
	certificateReadRepo := readmodel.NewCertificateReadRepo(db)
	getMyCertificatesHandler := app.NewGetMyCertificatesHandler(certificateReadRepo)
	getMyCoursesHandler := app.NewGetMyCoursesHandler(courseReadRepo)
	getMyEnrolledCoursesHandler := app.NewGetMyEnrolledCoursesHandler(courseReadRepo)
	getPublishedCoursesHandler := app.NewGetPublishedCoursesHandler(courseReadRepo)
	getSystemCoursesHandler := app.NewGetSystemCoursesHandler(courseReadRepo)
	getUploadVideoLessonURLHandler := app.NewGetUploadVideoLessonURLHandler(objectstorageS3)
	queries := app.NewQueries(handlerProvider, getCourseHandler, getCourseDetailHandler, getCourseForUpdateHandler, getCourseLandingPageHandler, getCourseReviewsHandler, getLessonCommentsHandler, getLessonDetailHandler, getLessonProgressHandler, getMyBookmarkedCoursesHandler, getMyCertificatesHandler, getMyCoursesHandler, getMyEnrolledCoursesHandler, getPublishedCoursesHandler, getSystemCoursesHandler, getUploadVideoLessonURLHandler)
>>>>>>> origin
	appApp := &app.App{
		Cmds:    cmds,
		Queries: queries,
	}
	server := &configConfig.Server
	strictHandler := http.NewStrictHandler(appApp, server)
	serverInterface := http.NewHandler(strictHandler)
	httpHTTP, cleanup4, err := http.New(ctx, engine, serverInterface, server, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serviceServer := grpc.NewServiceServer(appApp)
	loggingLogger := otel.MapSlogToGRPCMiddlewareLogger(logger)
	grpcGRPC, cleanup5, err := grpc.New(ctx, serviceServer, server, loggingLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	healthHealth := health.New(server)
	pg := persistence.NewPG(db)
	meterProvider, cleanup6, err := otel.NewMeterProvider(ctx, resource)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	global := otel.ProvideGlobal(loggerProvider, meterProvider, tracerProvider)
	courseServer := course.NewServer(httpHTTP, grpcGRPC, healthHealth, pg, global, logger)
	return courseServer, func() {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireServiceNameValue    = ServiceName
	_wireServiceVersionValue = ServiceVersion
)

// wire.go:

var ProviderSet = wire.NewSet(course.ProviderSet, wire.Value(ServiceName), wire.Value(ServiceVersion))
