// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/egolia-uit/egolia/internal/course"
	"github.com/egolia-uit/egolia/internal/course/app"
	"github.com/egolia-uit/egolia/internal/course/component"
	"github.com/egolia-uit/egolia/internal/course/config"
	"github.com/egolia-uit/egolia/internal/course/controller/grpc"
	"github.com/egolia-uit/egolia/internal/course/controller/health"
	"github.com/egolia-uit/egolia/internal/course/controller/http"
	"github.com/egolia-uit/egolia/internal/course/domain"
	"github.com/egolia-uit/egolia/internal/course/infra/objectstorage"
	"github.com/egolia-uit/egolia/internal/course/infra/persistence"
	"github.com/egolia-uit/egolia/internal/course/infra/persistence/readmodel"
	"github.com/egolia-uit/egolia/internal/course/infra/persistence/repo"
	"github.com/egolia-uit/egolia/pkg/common/http"
	"github.com/egolia-uit/egolia/pkg/logging"
	"github.com/egolia-uit/egolia/pkg/otel"
	"github.com/goforj/wire"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*course.Server, func(), error) {
	validate := component.ProvideValidate()
	viper := config.NewViper()
	configConfig, err := config.New(validate, viper)
	if err != nil {
		return nil, nil, err
	}
	log := &configConfig.Log
	stdoutHandler := logging.NewStdoutHandler(log)
	serviceName := _wireServiceNameValue
	serviceVersion := _wireServiceVersionValue
	resource, err := otel.NewResource(ctx, serviceName, serviceVersion)
	if err != nil {
		return nil, nil, err
	}
	loggerProvider, cleanup, err := otel.NewLoggerProvider(ctx, resource)
	if err != nil {
		return nil, nil, err
	}
	slogHandler := otel.NewSlogHandler(serviceName, loggerProvider)
	logger := logging.NewSlog(stdoutHandler, slogHandler, log)
	ginSlogHandlerFunc := commonhttp.NewGinSlogHandler(log, logger)
	otelGinHandlerFunc := commonhttp.NewOtelGinHandler(serviceName)
	general := &configConfig.General
	engine := commonhttp.NewGin(ginSlogHandlerFunc, otelGinHandlerFunc, general)
	db, cleanup2, err := persistence.NewDB(ctx, configConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	s3 := &configConfig.S3
	objectstorageS3, err := objectstorage.NewS3(ctx, s3)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	unitOfWork := repo.NewUnitOfWork(db, objectstorageS3)
	tracerProvider, cleanup3, err := otel.NewTracerProvider(ctx, resource)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tracer := app.NewTracer(tracerProvider)
	createCourseCmd := app.NewCreateCourseHandler(unitOfWork, logger, tracer)
	deleteCourseSvc := domain.NewDeleteCourseSvc()
	deleteCourseCmd := app.NewDeleteCourseHandler(deleteCourseSvc, unitOfWork, logger, tracer)
	enrollInCourseSvc := domain.NewEnrollInCourseSvc()
	enrollInCourseCmd := app.NewEnrollInCourseHandler(enrollInCourseSvc, unitOfWork, logger, tracer)
	finishCourseSvc := domain.NewFinishCourseSvc()
	finishCourseCmd := app.NewFinishCourseHandler(finishCourseSvc, unitOfWork, logger, tracer)
	moveLessonSvc := domain.NewMoveLessonSvc()
	moveLessonCmd := app.NewMoveLessonHandler(moveLessonSvc, unitOfWork, logger, tracer)
	enrollmentRepo := repo.NewEnrollmentRepo(db)
	reviewRepo := repo.NewReviewRepo(db)
	reviewCourseSvc := domain.NewReviewCourseSvc(enrollmentRepo, reviewRepo)
	reviewCourseCmd := app.NewReviewCourseHandler(reviewCourseSvc, unitOfWork, logger, tracer)
	updateCourseCmd := app.NewUpdateCourseHandler(unitOfWork, logger, tracer)
	cmds := &app.Cmds{
		CreateCourse:   createCourseCmd,
		DeleteCourse:   deleteCourseCmd,
		EnrollInCourse: enrollInCourseCmd,
		FinishCourse:   finishCourseCmd,
		MoveLesson:     moveLessonCmd,
		ReviewCourse:   reviewCourseCmd,
		UpdateCourse:   updateCourseCmd,
	}
	courseReadRepo := readmodel.NewCourseReadRepo(db, objectstorageS3)
	getCourseQuery := app.NewGetCourseHandler(courseReadRepo, logger, tracer)
	getCourseDetailQuery := app.NewGetCourseDetailHandler(courseReadRepo, logger, tracer)
	getCoursesQuery := app.NewGetCoursesHandler(courseReadRepo, logger, tracer)
	getInstructorCoursesQuery := app.NewGetInstructorCoursesHandler(courseReadRepo, logger, tracer)
	lessonReadRepo := readmodel.NewLessonReadRepo(db)
	getLessonDetailQuery := app.NewGetLessonDetailHandler(lessonReadRepo, logger, tracer)
	getUploadVideoLessonURLQuery := app.NewGetUploadVideoLessonURLHandler(objectstorageS3, logger, tracer)
	searchCoursesQuery := app.NewSearchCoursesHandler(courseReadRepo, logger, tracer)
	queries := &app.Queries{
		GetCourse:               getCourseQuery,
		GetCourseDetail:         getCourseDetailQuery,
		GetCourses:              getCoursesQuery,
		GetInstructorCourses:    getInstructorCoursesQuery,
		GetLessonDetail:         getLessonDetailQuery,
		GetUploadVideoLessonURL: getUploadVideoLessonURLQuery,
		SearchCourses:           searchCoursesQuery,
	}
	appApp := &app.App{
		Cmds:    cmds,
		Queries: queries,
	}
	server := &configConfig.Server
	strictHandler := http.NewStrictHandler(appApp, server)
	serverInterface := http.NewHandler(strictHandler)
	httpHTTP, cleanup4, err := http.New(ctx, engine, serverInterface, server, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serviceServer := grpc.NewServiceServer(appApp)
	loggingLogger := otel.MapSlogToGRPCMiddlewareLogger(logger)
	grpcGRPC, cleanup5, err := grpc.New(ctx, serviceServer, server, loggingLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	healthHealth := health.New(server)
	pg := persistence.NewPG(db)
	meterProvider, cleanup6, err := otel.NewMeterProvider(ctx, resource)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	global := otel.ProvideGlobal(loggerProvider, meterProvider, tracerProvider)
	courseServer := course.NewServer(httpHTTP, grpcGRPC, healthHealth, pg, global, logger)
	return courseServer, func() {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireServiceNameValue    = ServiceName
	_wireServiceVersionValue = ServiceVersion
)

// wire.go:

var ProviderSet = wire.NewSet(course.ProviderSet, wire.Value(ServiceName), wire.Value(ServiceVersion))
