// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateCourseData, CreateCourseErrors, CreateCourseResponses, CreateLessonData, CreateLessonErrors, CreateLessonResponses, GetCourseData, GetCourseErrors, GetCourseResponses } from './types.gen';
import { zCreateCourseData, zCreateCourseResponse, zCreateLessonData, zCreateLessonResponse, zGetCourseData, zGetCourseResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create course
 */
export const createCourse = <ThrowOnError extends boolean = false>(options?: Options<CreateCourseData, ThrowOnError>) => (options?.client ?? client).post<CreateCourseResponses, CreateCourseErrors, ThrowOnError>({
    requestValidator: async (data) => await zCreateCourseData.parseAsync(data),
    responseValidator: async (data) => await zCreateCourseResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/course/courses',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get course
 */
export const getCourse = <ThrowOnError extends boolean = false>(options: Options<GetCourseData, ThrowOnError>) => (options.client ?? client).get<GetCourseResponses, GetCourseErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetCourseData.parseAsync(data),
    responseValidator: async (data) => await zGetCourseResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/course/courses/{courseId}',
    ...options
});

/**
 * Create lesson
 */
export const createLesson = <ThrowOnError extends boolean = false>(options?: Options<CreateLessonData, ThrowOnError>) => (options?.client ?? client).post<CreateLessonResponses, CreateLessonErrors, ThrowOnError>({
    requestValidator: async (data) => await zCreateLessonData.parseAsync(data),
    responseValidator: async (data) => await zCreateLessonResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/course/lessons',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
