// This file is auto-generated by @hey-api/openapi-ts

import type { CheckoutCourseResponse, CommentOnPostResponse, CreatePostResponse, GetCertificateByIdResponse, GetCourseDetailResponse, GetCourseLandingPageResponse, GetInstructorCoursesResponse, GetLessonCommentsResponse, GetMyCertificatesResponse, GetMyEnrolledCoursesResponse, GetPlatformRevenueAnalyticsResponse, GetPostByIdResponse, GetPostCommentsResponse, GetPublishedCoursesResponse, GetSystemCoursesResponse, GetTransactionsResponse, GetUploadVideoLessonUrlResponse, ReplyCommentResponse, SearchCoursesResponse, SearchPostsResponse, UpdateCommentResponse, UpdatePostResponse } from './types.gen';

const courseCourseSchemaResponseTransformer = (data: any) => {
    data.price = BigInt(data.price.toString());
    return data;
};

export const searchCoursesResponseTransformer = async (data: any): Promise<SearchCoursesResponse> => {
    data.data = data.data.map((item: any) => courseCourseSchemaResponseTransformer(item));
    return data;
};

export const getSystemCoursesResponseTransformer = async (data: any): Promise<GetSystemCoursesResponse> => {
    data.data = data.data.map((item: any) => courseCourseSchemaResponseTransformer(item));
    return data;
};

export const getPublishedCoursesResponseTransformer = async (data: any): Promise<GetPublishedCoursesResponse> => {
    data.data = data.data.map((item: any) => courseCourseSchemaResponseTransformer(item));
    return data;
};

export const getInstructorCoursesResponseTransformer = async (data: any): Promise<GetInstructorCoursesResponse> => {
    data.data = data.data.map((item: any) => courseCourseSchemaResponseTransformer(item));
    return data;
};

const courseCourseDetailSchemaResponseTransformer = (data: any) => {
    data.course = courseCourseSchemaResponseTransformer(data.course);
    return data;
};

export const getCourseDetailResponseTransformer = async (data: any): Promise<GetCourseDetailResponse> => {
    data.data = courseCourseDetailSchemaResponseTransformer(data.data);
    return data;
};

const courseCourseLandingPageSchemaResponseTransformer = (data: any) => {
    data.course = courseCourseDetailSchemaResponseTransformer(data.course);
    return data;
};

export const getCourseLandingPageResponseTransformer = async (data: any): Promise<GetCourseLandingPageResponse> => {
    data.data = courseCourseLandingPageSchemaResponseTransformer(data.data);
    return data;
};

export const getMyEnrolledCoursesResponseTransformer = async (data: any): Promise<GetMyEnrolledCoursesResponse> => {
    data.data = data.data.map((item: any) => courseCourseSchemaResponseTransformer(item));
    return data;
};

const courseUploadVideoUrlResponseSchemaResponseTransformer = (data: any) => {
    data.expiresAt = new Date(data.expiresAt);
    return data;
};

export const getUploadVideoLessonUrlResponseTransformer = async (data: any): Promise<GetUploadVideoLessonUrlResponse> => {
    data.data = courseUploadVideoUrlResponseSchemaResponseTransformer(data.data);
    return data;
};

const courseLessonCommentSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const getLessonCommentsResponseTransformer = async (data: any): Promise<GetLessonCommentsResponse> => {
    data.data = data.data.map((item: any) => courseLessonCommentSchemaResponseTransformer(item));
    return data;
};

const courseCertificateSchemaResponseTransformer = (data: any) => {
    data.issuedAt = new Date(data.issuedAt);
    return data;
};

export const getMyCertificatesResponseTransformer = async (data: any): Promise<GetMyCertificatesResponse> => {
    data.data = data.data.map((item: any) => courseCertificateSchemaResponseTransformer(item));
    return data;
};

export const getCertificateByIdResponseTransformer = async (data: any): Promise<GetCertificateByIdResponse> => {
    data.data = courseCertificateSchemaResponseTransformer(data.data);
    return data;
};

const billingTransactionSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    if (data.issuedAt) {
        data.issuedAt = new Date(data.issuedAt);
    }
    return data;
};

export const checkoutCourseResponseTransformer = async (data: any): Promise<CheckoutCourseResponse> => {
    data = billingTransactionSchemaResponseTransformer(data);
    return data;
};

const billingRevenueAnalyticsSchemaResponseTransformer = (data: any) => {
    data.from = new Date(data.from);
    data.to = new Date(data.to);
    data.totalRevenue = BigInt(data.totalRevenue.toString());
    return data;
};

export const getPlatformRevenueAnalyticsResponseTransformer = async (data: any): Promise<GetPlatformRevenueAnalyticsResponse> => {
    data = billingRevenueAnalyticsSchemaResponseTransformer(data);
    return data;
};

export const getTransactionsResponseTransformer = async (data: any): Promise<GetTransactionsResponse> => {
    data.data = data.data.map((item: any) => billingTransactionSchemaResponseTransformer(item));
    return data;
};

const blogPostSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const searchPostsResponseTransformer = async (data: any): Promise<SearchPostsResponse> => {
    data.data = data.data.map((item: any) => blogPostSchemaResponseTransformer(item));
    return data;
};

export const createPostResponseTransformer = async (data: any): Promise<CreatePostResponse> => {
    data = blogPostSchemaResponseTransformer(data);
    return data;
};

export const getPostByIdResponseTransformer = async (data: any): Promise<GetPostByIdResponse> => {
    data = blogPostSchemaResponseTransformer(data);
    return data;
};

export const updatePostResponseTransformer = async (data: any): Promise<UpdatePostResponse> => {
    data = blogPostSchemaResponseTransformer(data);
    return data;
};

const blogCommentSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const getPostCommentsResponseTransformer = async (data: any): Promise<GetPostCommentsResponse> => {
    data.data = data.data.map((item: any) => blogCommentSchemaResponseTransformer(item));
    return data;
};

export const commentOnPostResponseTransformer = async (data: any): Promise<CommentOnPostResponse> => {
    data = blogCommentSchemaResponseTransformer(data);
    return data;
};

export const updateCommentResponseTransformer = async (data: any): Promise<UpdateCommentResponse> => {
    data = blogCommentSchemaResponseTransformer(data);
    return data;
};

export const replyCommentResponseTransformer = async (data: any): Promise<ReplyCommentResponse> => {
    data = blogCommentSchemaResponseTransformer(data);
    return data;
};
