// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://api.egolia.localhost' | (string & {});
};

export type Course = {
    readonly id?: string;
};

export type Error = {
    /**
     * Error code
     */
    code: string;
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * URL with more information about the error
     */
    more_info?: string;
};

export type CreateCourseData = {
    body?: Course;
    path?: never;
    query?: never;
    url: '/course/courses';
};

export type CreateCourseErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Forbidden Error response
     */
    403: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type CreateCourseError = CreateCourseErrors[keyof CreateCourseErrors];

export type CreateCourseResponses = {
    /**
     * Course created
     */
    201: Course;
};

export type CreateCourseResponse = CreateCourseResponses[keyof CreateCourseResponses];
