// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zCourseCourseStatus = z.enum([
    'draft',
    'approved',
    'published',
    'archived'
]).default('draft');

/**
 * User ID from Authentik (need to change subject mode to User's ID instead of hashed)
 */
export const zCourseId = z.string();

export const zCourseCourse = z.object({
    id: z.uuid().readonly(),
    title: z.string(),
    instructorId: zCourseId,
    status: zCourseCourseStatus,
    price: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zCoursePagination = z.object({
    page: z.int().gte(1),
    limit: z.int().gte(1).lte(100),
    total: z.int().gte(0),
    totalPages: z.int().gte(0),
    hasNext: z.boolean(),
    hasPrev: z.boolean()
});

export const zCourseError = z.object({
    code: z.string(),
    message: z.string(),
    more_info: z.string().optional()
});

export const zCoursePropertiesId = z.uuid().readonly();

export const zCourseSection = z.object({
    id: z.uuid().readonly(),
    courseId: zCoursePropertiesId,
    title: z.string().min(1).max(255)
});

export const zCourseLessonType = z.enum(['video', 'test']);

export const zCourseLesson = z.object({
    id: z.uuid().readonly(),
    courseId: zCoursePropertiesId,
    title: z.string(),
    lessonType: zCourseLessonType
});

export const zCourseCourseDetailSectionItem = z.object({
    section: zCourseSection.and(z.object({
        lessons: z.array(zCourseLesson)
    })).optional()
});

export const zCourseCourseDetail = z.object({
    course: zCourseCourse,
    sections: z.array(zCourseCourseDetailSectionItem)
});

export const zCourseCourseProgress = z.object({
    courseId: zCoursePropertiesId,
    userId: zCourseId,
    totalLessons: z.int().gte(0).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    completedLessons: z.int().gte(0).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    progressPercent: z.number().gte(0).lte(100),
    isCompleted: z.boolean()
});

export const zCourseCourseLandingPage = z.object({
    course: zCourseCourseDetail,
    overview: z.string(),
    introduction: z.object({
        videoUrl: z.url()
    })
});

export const zCourseVideoLesson = zCourseLesson.and(z.object({
    videoUrl: z.url().readonly(),
    duration: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
}));

export const zCourseTestAnswer = z.object({
    id: z.uuid().readonly(),
    content: z.string().min(1).max(1000),
    isCorrect: z.boolean()
});

export const zCourseTestQuestion = z.object({
    id: z.uuid().readonly(),
    question: z.string().min(1).max(2000),
    answers: z.array(zCourseTestAnswer).min(1)
});

export const zCourseTestLesson = zCourseLesson.and(z.object({
    type: z.enum(['multipleChoice', 'singleChoice']),
    questions: z.array(z.unknown())
}));

export const zCourseLessonDetail = z.union([
    zCourseVideoLesson,
    zCourseTestLesson
]);

export const zCourseTestLessonType = z.enum(['multipleChoice', 'singleChoice']);

export const zCourseLessonPropertiesId = z.uuid().readonly();

export const zCourseLessonProgress = z.object({
    id: z.uuid().readonly(),
    userId: zCourseId,
    lessonId: zCourseLessonPropertiesId,
    isCompleted: z.boolean()
});

export const zCourseVideoLessonProgress = zCourseLessonProgress.and(z.object({
    watchedSeconds: z.number().gte(0)
}));

export const zCourseTestLessonProgress = zCourseLessonProgress.and(z.object({
    score: z.number().gte(0).lte(100)
}));

export const zCourseLessonComment = z.object({
    id: z.uuid().readonly(),
    userId: zCourseId,
    lessonId: zCourseLessonPropertiesId,
    content: z.string().min(1).max(4000),
    createdAt: z.iso.datetime(),
    parentCommentId: z.uuid().nullish()
});

export const zCourseContent = z.string().min(1).max(4000);

export const zCourseCertificate = z.object({
    id: z.uuid().readonly(),
    courseId: zCoursePropertiesId,
    userId: zCourseId,
    issuedAt: z.iso.datetime()
});

/**
 * User ID from Authentik (need to change subject mode to User's ID instead of hashed)
 */
export const zBillingId = z.string();

/**
 * Username from Authentik
 */
export const zBillingUsername = z.string();

/**
 * Email from Authentik
 */
export const zBillingEmail = z.email().nullable();

export const zBillingTitle = z.string();

/**
 * Current status of a billing transaction
 */
export const zBillingTransactionStatus = z.enum([
    'pending',
    'completed',
    'failed'
]);

export const zBillingTransaction = z.object({
    id: z.uuid().readonly(),
    userId: zBillingId,
    username: zBillingUsername,
    userEmail: zBillingEmail,
    courseId: z.uuid(),
    courseTitle: zBillingTitle.optional(),
    amount: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).readonly(),
    status: zBillingTransactionStatus,
    createdAt: z.iso.datetime().readonly()
});

export const zBillingError = z.object({
    code: z.string(),
    message: z.string(),
    more_info: z.string().optional()
});

export const zBillingRevenueAnalytics = z.object({
    from: z.iso.datetime(),
    to: z.iso.datetime(),
    totalRevenue: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    completedTransactions: z.int().gte(0),
    failedTransactions: z.int().gte(0)
});

export const zBillingPagination = z.object({
    page: z.int().gte(1),
    limit: z.int().gte(1).lte(100),
    total: z.int().gte(0),
    totalPages: z.int().gte(0),
    hasNext: z.boolean(),
    hasPrev: z.boolean()
});

/**
 * User ID from Authentik (need to change subject mode to User's ID instead of hashed)
 */
export const zBlogId = z.string();

export const zBlogPost = z.object({
    id: z.uuid().readonly(),
    authorId: zBlogId,
    title: z.string(),
    content: z.string().min(1),
    tags: z.array(z.string()),
    createdAt: z.iso.datetime().readonly(),
    commentCount: z.int().gte(0).readonly()
});

export const zBlogPagination = z.object({
    page: z.int().gte(1),
    limit: z.int().gte(1).lte(100),
    total: z.int().gte(0),
    totalPages: z.int().gte(0),
    hasNext: z.boolean(),
    hasPrev: z.boolean()
});

export const zBlogError = z.object({
    code: z.string(),
    message: z.string(),
    more_info: z.string().optional()
});

export const zBlogComment = z.object({
    id: z.uuid().readonly(),
    postId: z.uuid().readonly(),
    authorId: zBlogId,
    content: z.string().min(1),
    parentCommentId: z.uuid().readonly().nullable(),
    createdAt: z.iso.datetime().readonly()
});

export const zCourseCourseWritable = z.object({
    title: z.string(),
    status: zCourseCourseStatus,
    price: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zCourseSectionWritable = z.object({
    title: z.string().min(1).max(255)
});

export const zCourseLessonWritable = z.object({
    title: z.string()
});

export const zCourseCourseDetailSectionItemWritable = z.object({
    section: zCourseSectionWritable.and(z.object({
        lessons: z.array(zCourseLessonWritable)
    })).optional()
});

export const zCourseCourseDetailWritable = z.object({
    course: zCourseCourseWritable,
    sections: z.array(zCourseCourseDetailSectionItemWritable)
});

export const zCourseCourseProgressWritable = z.object({
    userId: zCourseId,
    totalLessons: z.int().gte(0).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    completedLessons: z.int().gte(0).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    progressPercent: z.number().gte(0).lte(100),
    isCompleted: z.boolean()
});

export const zCourseCourseLandingPageWritable = z.object({
    course: zCourseCourseDetailWritable,
    overview: z.string(),
    introduction: z.object({
        videoUrl: z.url()
    })
});

export const zCourseVideoLessonWritable = zCourseLessonWritable.and(z.object({
    videoKey: z.string().optional(),
    duration: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
}));

export const zCourseTestAnswerWritable = z.object({
    content: z.string().min(1).max(1000),
    isCorrect: z.boolean()
});

export const zCourseTestQuestionWritable = z.object({
    question: z.string().min(1).max(2000),
    answers: z.array(zCourseTestAnswerWritable).min(1)
});

export const zCourseTestLessonWritable = zCourseLessonWritable.and(z.object({
    type: z.enum(['multipleChoice', 'singleChoice']),
    questions: z.array(z.unknown())
}));

export const zCourseLessonDetailWritable = z.union([
    zCourseVideoLessonWritable,
    zCourseTestLessonWritable
]);

export const zCourseLessonProgressWritable = z.object({
    isCompleted: z.boolean()
});

export const zCourseVideoLessonProgressWritable = zCourseLessonProgressWritable.and(z.object({
    watchedSeconds: z.number().gte(0)
}));

export const zCourseTestLessonProgressWritable = zCourseLessonProgressWritable.and(z.object({
    score: z.number().gte(0).lte(100)
}));

export const zCourseLessonCommentWritable = z.object({
    userId: zCourseId,
    content: z.string().min(1).max(4000),
    createdAt: z.iso.datetime(),
    parentCommentId: z.uuid().nullish()
});

export const zCourseCertificateWritable = z.object({
    userId: zCourseId,
    issuedAt: z.iso.datetime()
});

export const zBillingTransactionWritable = z.object({
    courseId: z.uuid()
});

export const zBlogPostWritable = z.object({
    title: z.string(),
    content: z.string().min(1),
    tags: z.array(z.string())
});

export const zBlogCommentWritable = z.object({
    content: z.string().min(1)
});

export const zCourseStatusQuery = zCourseCourseStatus;

/**
 * Page number for pagination
 */
export const zCoursePageQuery = z.int().gte(1).default(1);

/**
 * Number of items per page
 */
export const zCourseLimitQuery = z.int().gte(1).lte(100).default(20);

/**
 * Sort order
 */
export const zCourseOrderQuery = z.enum(['asc', 'desc']).default('desc');

export const zCourseInstructorIdPath = z.uuid();

export const zCourseCourseIdPath = zCoursePropertiesId;

export const zCourseSectionIdPath = z.uuid();

export const zCourseLessonIdPath = z.uuid();

/**
 * Unique identifier of the post comment
 */
export const zCourseCommentIdPath = z.uuid();

export const zCourseCertificateIdPath = z.uuid();

/**
 * Page number for pagination
 */
export const zBillingPageQuery = z.int().gte(1).default(1);

/**
 * Number of items per page
 */
export const zBillingLimitQuery = z.int().gte(1).lte(100).default(20);

/**
 * Sort order
 */
export const zBillingOrderQuery = z.enum(['asc', 'desc']).default('desc');

/**
 * Unique identifier of the billing transaction
 */
export const zBillingTransactionIdPath = z.uuid();

/**
 * Page number for pagination
 */
export const zBlogPageQuery = z.int().gte(1).default(1);

/**
 * Number of items per page
 */
export const zBlogLimitQuery = z.int().gte(1).lte(100).default(20);

/**
 * Sort order
 */
export const zBlogOrderQuery = z.enum(['asc', 'desc']).default('desc');

/**
 * Unique identifier of the blog post
 */
export const zBlogPostIdPath = z.uuid();

/**
 * Unique identifier of the post comment
 */
export const zBlogCommentIdPath = z.uuid();

export const zSearchCoursesQuery = z.object({
    q: z.string().optional(),
    status: zCourseCourseStatus.optional(),
    instructorId: z.array(z.uuid()).optional(),
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(100).optional().default(20),
    order: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * Search results for courses
 */
export const zSearchCoursesResponse = z.object({
    data: z.array(zCourseCourse),
    pagination: zCoursePagination
});

export const zCreateCourseBody = zCourseCourseWritable;

export const zGetSystemCoursesQuery = z.object({
    status: zCourseCourseStatus.optional(),
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(100).optional().default(20),
    order: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * Courses in system
 */
export const zGetSystemCoursesResponse = z.object({
    data: z.array(zCourseCourse),
    pagination: zCoursePagination
});

export const zGetPublishedCoursesQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(100).optional().default(20),
    order: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * Published courses
 */
export const zGetPublishedCoursesResponse = z.object({
    data: z.array(zCourseCourse),
    pagination: zCoursePagination
});

export const zGetInstructorCoursesPath = z.object({
    instructorId: z.uuid()
});

export const zGetInstructorCoursesQuery = z.object({
    status: zCourseCourseStatus.optional(),
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(100).optional().default(20),
    order: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * Courses by instructor
 */
export const zGetInstructorCoursesResponse = z.object({
    data: z.array(zCourseCourse),
    pagination: zCoursePagination
});

export const zDeleteCoursePath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Course successfully deleted
 */
export const zDeleteCourseResponse = z.void();

export const zGetCourseDetailPath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Full course content with section and lesson references
 */
export const zGetCourseDetailResponse = z.object({
    data: zCourseCourseDetail
});

export const zUpdatedCourseBody = z.object({
    title: z.string().min(1).max(255).optional(),
    slug: z.string().min(1).max(255).optional(),
    status: zCourseCourseStatus.optional(),
    price: z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

export const zUpdatedCoursePath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Course basic information updated
 */
export const zUpdatedCourseResponse = z.void();

export const zEnrollInCoursePath = z.object({
    courseId: zCoursePropertiesId
});

export const zGetCourseProgressPath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Course progress
 */
export const zGetCourseProgressResponse = z.object({
    data: zCourseCourseProgress
});

export const zFinishCoursePath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Course finished and certificate issued
 */
export const zFinishCourseResponse = z.void();

export const zReviewCourseBody = z.object({
    rating: z.int().gte(1).lte(5),
    comment: z.string().max(2000)
});

export const zReviewCoursePath = z.object({
    courseId: zCoursePropertiesId
});

export const zBookmarkCoursePath = z.object({
    courseId: zCoursePropertiesId
});

export const zUnbookmarkCoursePath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Course unbookmarked successfully
 */
export const zUnbookmarkCourseResponse = z.void();

export const zTriggerLearningReminderBody = z.object({
    dryRun: z.boolean().optional()
});

export const zTriggerLearningReminderPath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Learning reminder triggered
 */
export const zTriggerLearningReminderResponse = z.void();

export const zGetCourseLandingPagePath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Course landing page data
 */
export const zGetCourseLandingPageResponse = z.object({
    data: zCourseCourseLandingPage
});

export const zApproveCoursePath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Course approved
 */
export const zApproveCourseResponse = z.void();

export const zDeclineCourseBody = z.object({
    reason: z.string().max(1000).optional()
});

export const zDeclineCoursePath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Course declined
 */
export const zDeclineCourseResponse = z.void();

export const zHideCoursePath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Course hidden
 */
export const zHideCourseResponse = z.void();

export const zUnhideCoursePath = z.object({
    courseId: zCoursePropertiesId
});

/**
 * Course unhidden
 */
export const zUnhideCourseResponse = z.void();

export const zGetMyEnrolledCoursesQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(100).optional().default(20),
    order: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * My enrolled courses
 */
export const zGetMyEnrolledCoursesResponse = z.object({
    data: z.array(zCourseCourse),
    pagination: zCoursePagination
});

export const zCreateSectionBody = z.object({
    courseId: zCoursePropertiesId,
    title: z.string().min(1).max(255),
    previousSectionId: z.uuid().nullable()
});

export const zDeleteSectionPath = z.object({
    sectionId: z.uuid()
});

/**
 * Section successfully deleted
 */
export const zDeleteSectionResponse = z.void();

export const zCreateLessonBody = z.object({
    video: zCourseVideoLessonWritable.optional(),
    test: zCourseTestLessonWritable.optional()
});

export const zDeleteLessonPath = z.object({
    lessonId: z.uuid()
});

/**
 * Lesson successfully deleted
 */
export const zDeleteLessonResponse = z.void();

export const zGetLessonDetailPath = z.object({
    lessonId: z.uuid()
});

/**
 * Lesson detail
 */
export const zGetLessonDetailResponse = z.object({
    data: zCourseLessonDetail
});

export const zEditVideoLessonBody = zCourseVideoLessonWritable;

export const zEditVideoLessonPath = z.object({
    lessonId: z.uuid()
});

/**
 * Video lesson successfully updated
 */
export const zEditVideoLessonResponse = z.void();

export const zEditTestLessonBody = zCourseTestLessonWritable;

export const zEditTestLessonPath = z.object({
    lessonId: z.uuid()
});

/**
 * Test lesson successfully updated
 */
export const zEditTestLessonResponse = z.void();

export const zGetUploadVideoLessonUrlPath = z.object({
    lessonId: z.uuid()
});

/**
 * Upload URL generated
 */
export const zGetUploadVideoLessonUrlResponse = z.object({
    uploadUrl: z.url(),
    videoKey: z.string(),
    expiresAt: z.iso.datetime()
});

export const zCreateTestBody = z.object({
    type: zCourseTestLessonType,
    questions: z.array(zCourseTestQuestionWritable).min(1)
});

export const zCreateTestPath = z.object({
    lessonId: z.uuid()
});

export const zGetLessonProgressPath = z.object({
    lessonId: z.uuid()
});

/**
 * Lesson progress
 */
export const zGetLessonProgressResponse = z.object({
    data: z.union([
        zCourseVideoLessonProgress,
        zCourseTestLessonProgress
    ])
});

export const zSaveVideoLessonProgressBody = zCourseVideoLessonProgressWritable;

export const zSaveVideoLessonProgressPath = z.object({
    lessonId: z.uuid()
});

/**
 * Video lesson progress saved
 */
export const zSaveVideoLessonProgressResponse = z.void();

export const zSaveTestLessonProgressBody = zCourseTestLessonProgressWritable;

export const zSaveTestLessonProgressPath = z.object({
    lessonId: z.uuid()
});

/**
 * Test lesson progress saved
 */
export const zSaveTestLessonProgressResponse = z.object({
    data: zCourseTestLessonProgress
});

export const zMarkLessonAsCompletedPath = z.object({
    lessonId: z.uuid()
});

/**
 * Lesson marked as completed
 */
export const zMarkLessonAsCompletedResponse = z.void();

export const zMoveLessonBody = z.object({
    type: zCourseLessonType,
    sectionId: z.uuid(),
    afterLesson: z.object({
        id: z.uuid(),
        type: zCourseLessonType
    }).nullable()
});

export const zMoveLessonPath = z.object({
    lessonId: z.uuid()
});

export const zGetLessonCommentsPath = z.object({
    lessonId: z.uuid()
});

/**
 * Top-level comments for the lesson
 */
export const zGetLessonCommentsResponse = z.object({
    data: z.array(zCourseLessonComment)
});

export const zCommentOnLessonBody = z.object({
    content: zCourseContent
});

export const zCommentOnLessonPath = z.object({
    lessonId: z.uuid()
});

export const zReplyLessonCommentBody = z.object({
    content: zCourseContent
});

export const zReplyLessonCommentPath = z.object({
    commentId: z.uuid()
});

export const zGetMyCertificatesQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(100).optional().default(20),
    order: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * My certificates
 */
export const zGetMyCertificatesResponse = z.object({
    data: z.array(zCourseCertificate),
    pagination: zCoursePagination
});

export const zGetCertificateByIdPath = z.object({
    certificateId: z.uuid()
});

/**
 * Certificate detail
 */
export const zGetCertificateByIdResponse = z.object({
    data: zCourseCertificate
});

export const zCheckoutCourseBody = zBillingTransactionWritable;

/**
 * Checkout transaction created
 */
export const zCheckoutCourseResponse = zBillingTransaction;

export const zGetPlatformRevenueAnalyticsQuery = z.object({
    from: z.iso.date(),
    to: z.iso.date()
});

/**
 * Revenue analytics
 */
export const zGetPlatformRevenueAnalyticsResponse = zBillingRevenueAnalytics;

export const zGetTransactionsQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(100).optional().default(20),
    order: z.enum(['asc', 'desc']).optional().default('desc'),
    courseId: z.uuid().optional(),
    learnerId: zBillingId.optional()
});

/**
 * Learner billing history
 */
export const zGetTransactionsResponse = z.object({
    data: z.array(zBillingTransaction),
    pagination: zBillingPagination
});

export const zCompleteTransactionPath = z.object({
    transactionId: z.uuid()
});

/**
 * Transaction completed successfully
 */
export const zCompleteTransactionResponse = z.void();

export const zSearchPostsQuery = z.object({
    q: z.string().optional(),
    tag: z.string().optional(),
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(100).optional().default(20),
    order: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * Matched blog posts
 */
export const zSearchPostsResponse = z.object({
    data: z.array(zBlogPost),
    pagination: zBlogPagination
});

export const zCreatePostBody = zBlogPostWritable;

/**
 * Post created
 */
export const zCreatePostResponse = zBlogPost;

export const zDeletePostPath = z.object({
    postId: z.uuid()
});

/**
 * Post deleted successfully
 */
export const zDeletePostResponse = z.void();

export const zGetPostByIdPath = z.object({
    postId: z.uuid()
});

/**
 * Blog post detail
 */
export const zGetPostByIdResponse = zBlogPost;

export const zUpdatePostBody = z.object({
    title: z.string(),
    content: z.string().min(1),
    tags: z.array(z.string())
});

export const zUpdatePostPath = z.object({
    postId: z.uuid()
});

/**
 * Post updated
 */
export const zUpdatePostResponse = zBlogPost;

export const zGetPostCommentsPath = z.object({
    postId: z.uuid()
});

/**
 * Top-level comments for the post
 */
export const zGetPostCommentsResponse = z.object({
    data: z.array(zBlogComment)
});

export const zCommentOnPostBody = zBlogCommentWritable;

export const zCommentOnPostPath = z.object({
    postId: z.uuid()
});

/**
 * Comment created
 */
export const zCommentOnPostResponse = zBlogComment;

export const zDeleteCommentPath = z.object({
    commentId: z.uuid()
});

/**
 * Comment deleted successfully
 */
export const zDeleteCommentResponse = z.void();

export const zUpdateCommentBody = zBlogCommentWritable;

export const zUpdateCommentPath = z.object({
    commentId: z.uuid()
});

/**
 * Comment updated
 */
export const zUpdateCommentResponse = zBlogComment;

export const zReplyCommentBody = zBlogCommentWritable;

export const zReplyCommentPath = z.object({
    commentId: z.uuid()
});

/**
 * Reply created
 */
export const zReplyCommentResponse = zBlogComment;
