# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json
http:
  routers:
    billing:
      entryPoints:
        - web
      rule: Host(`api.egolia.localhost`) && PathPrefix(`/billing`)
      service: billing
      middlewares:
        - jwt
    billing-health:
      entryPoints:
        - web
      rule: Host(`api.egolia.localhost`) && PathPrefix(`/billing/health`)
      service: billing-health

  services:
    billing:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8082
    billing-health:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:28082
