# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json
http:
  routers:
    blog-http:
      entryPoints:
        - web
      rule: Host(`api.egolia.localhost`) && PathPrefix(`/blog`)
      service: blog-http
      middlewares:
        - jwt

    blog-health:
      entryPoints:
        - web
      rule: Host(`api.egolia.localhost`) && PathPrefix(`/blog/health`)
      service: blog-health

  services:
    blog-http:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8083
    blog-health:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:28083
