# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json
http:
  middlewares:
    cors:
      headers:
        accessControlAllowOriginList:
          - http://localhost:3000
          - http://localhost:9080
          - http://web.egolia.localhost
          - http://api.egolia.localhost
        accessControlAllowMethods: '*'
        accessControlAllowHeaders: '*'
        accessControlAllowCredentials: true
