# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json
http:
  routers:
    course-preflight:
      entryPoints:
        - web
      rule: Host(`api.egolia.localhost`) && Method(`OPTIONS`) && PathPrefix(`/course`)
      service: course-http
      middlewares:
        - cors

    course-http-admin:
      entryPoints:
        - web
      rule: "
        Host(`api.egolia.localhost`) && ( \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/approve`) && Method(`POST`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/decline`) && Method(`POST`)) \
        ) \
        "
      service: course-http
      priority: 85
      middlewares:
        - cors
        - protect-admin

    course-http-instructor:
      entryPoints:
        - web
      rule: "
        Host(`api.egolia.localhost`) && ( \
        (Path(`/course/my-courses`) && Method(`GET`)) || \
        (Path(`/course/courses-system`) && Method(`GET`)) || \
        (Path(`/course/courses`) && Method(`POST`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}`) && Method(`DELETE`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/analytics`) && Method(`GET`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/basic-info`) && Method(`PUT`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/hide`) && (Method(`POST`) || Method(`DELETE`))) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/students`) && Method(`GET`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/upload-video-url`) && Method(`POST`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/sections`) && Method(`POST`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/sections/{sectionId:[a-zA-Z0-9-]+}`) && (Method(`DELETE`) || Method(`PATCH`))) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/sections/{sectionId:[a-zA-Z0-9-]+}/move`) && Method(`POST`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/sections/{sectionId:[a-zA-Z0-9-]+}/lessons`) && Method(`POST`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/sections/{sectionId:[a-zA-Z0-9-]+}/lessons/{lessonId:[a-zA-Z0-9-]+}`) && Method(`DELETE`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/sections/{sectionId:[a-zA-Z0-9-]+}/lessons/{lessonId:[a-zA-Z0-9-]+}/move`) && Method(`POST`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/sections/{sectionId:[a-zA-Z0-9-]+}/lessons/{lessonId:[a-zA-Z0-9-]+}/test`) && Method(`PUT`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/sections/{sectionId:[a-zA-Z0-9-]+}/lessons/{lessonId:[a-zA-Z0-9-]+}/video`) && Method(`PATCH`)) || \
        (Path(`/course/lesson-comments/{commentId:[a-zA-Z0-9-]+}`) && Method(`DELETE`)) \
        ) \
        "
      service: course-http
      priority: 80
      middlewares:
        - cors
        - protect-instructor-or-admin

    course-http-public:
      entryPoints:
        - web
      rule: "
        Host(`api.egolia.localhost`) && ( \
        PathPrefix(`/course/courses-published`) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/landing`) && Method(`GET`)) || \
        (Path(`/course/courses/{courseId:[a-zA-Z0-9-]+}/reviews`) && Method(`GET`)) \
        ) \
        "
      service: course-http
      priority: 70
      middlewares:
        - cors

    course-http-authenticated:
      entryPoints:
        - web
      rule: "
        Host(`api.egolia.localhost`) && ( \
        PathPrefix(`/course/`) \
        ) \
        "
      service: course-http
      priority: 50
      middlewares:
        - cors
        - authenticated

    course-grpc:
      entryPoints:
        - web
      rule: Host(`api.egolia.localhost`) && PathPrefix(`/course.CourseService/`)
      priority: 90
      service: course-grpc

    course-health:
      entryPoints:
        - web
      rule: Host(`api.egolia.localhost`) && PathPrefix(`/course/health`)
      priority: 100
      service: course-health
      middlewares:
        - cors

  services:
    course-http:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8081

    course-grpc:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:18081

    course-health:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:28081
