# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json
http:
  routers:
    course-admin:
      entryPoints:
        - web
      rule: Host(`api.egolia.localhost`) && PathPrefix(`/course`)
      service: course
      middlewares:
        - protect-admin

    course-instructor-or-admin:
      entryPoints:
        - web
      rule: Host(`api.egolia.localhost`) && PathPrefix(`/course`)
      service: course
      middlewares:
        - protect-instructor-or-admin

    course-public:
      entryPoints:
        - web
      rule: "
        Host(`api.egolia.localhost`) && ( \
        PathPrefix(`/course/courses-published`) || \
        PathPrefix(`/course/courses/{courseId:[a-zA-Z0-9-]+}/detail`) || \
        PathPrefix(`/course/certificates/{certificateId:[a-zA-Z0-9-]+}`) \
        ) \
        "
      service: course

    course-health:
      entryPoints:
        - web
      rule: Host(`api.egolia.localhost`) && PathPrefix(`/course/health`)
      service: course-health

  services:
    course:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:18081
    course-health:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:28081
