# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json
http:
  middlewares:
    protect-instructor:
      plugin:
        jwt:
          issuers: &issuers
            - issuer: http://authentik.egolia.localhost/application/o/api-web/
              jwks: http://authentik.egolia.localhost/application/o/api-web/jwks/
            - issuer: http://authentik.egolia.localhost/application/o/app-web/
              jwks: http://authentik.egolia.localhost/application/o/app-web/jwks/
          headerMap: &headerMap
            X-Forwarded-ID: sub
            X-Forwarded-Roles: roles
          require:
            role: instructor

    protect-admin:
      plugin:
        jwt:
          issuers: *issuers
          headerMap: *headerMap
          require:
            role: admin

    protect-instructor-or-admin:
      plugin:
        jwt:
          issuers: *issuers
          headerMap: *headerMap
          require:
            or:
              - role: instructor
              - role: admin
