## yaml-language-server: $schema=https://www.schemastore.org/openapi-3.X.json
openapi: 3.0.4

servers:
  - url: http://api.egolia.localhost

info:
  description: >
    Egolia API
  version: 0.0.0
  title: Egolia API
  license:
    name: MIT
    url: https://github.com/egolia-uit/egolia/blob/main/LICENSE
  contact:
    name: Egolia Support
    email: egolia@googlegroups.com
  x-apiName: course

tags:
  - name: Course
    description: Course
  - name: Section
    description: Section
  - name: Lesson
    description: Lesson
  - name: Test
    description: Test

paths:
  /course/courses:
    $ref: ./paths/courses.yaml
  /course/courses-system:
    $ref: ./paths/courses-system.yaml
  /course/courses-published:
    $ref: ./paths/courses-published.yaml
  /course/courses-by-instructor/{instructorId}:
    $ref: ./paths/courses-by-instructor_{instructorId}.yaml
  /course/courses/{courseId}:
    $ref: ./paths/courses_{courseId}.yaml
  /course/courses/{courseId}/approve:
    $ref: ./paths/courses_{courseId}_approve.yaml
  /course/courses/{courseId}/decline:
    $ref: ./paths/courses_{courseId}_decline.yaml
  /course/courses/{courseId}/hide:
    $ref: ./paths/courses_{courseId}_hide.yaml
  /course/courses/{courseId}/unhide:
    $ref: ./paths/courses_{courseId}_unhide.yaml

  /course/sections:
    $ref: ./paths/sections.yaml
  /course/sections/{sectionId}:
    $ref: ./paths/sections_{sectionId}.yaml

  /course/lessons:
    $ref: ./paths/lessons.yaml
  /course/lessons/{lessonId}:
    $ref: ./paths/lessons_{lessonId}.yaml
  /course/lessons/{lessonId}/upload-video-url:
    $ref: ./paths/lessons_{lessonId}_upload-video-url.yaml
  /course/lessons/{lessonId}/tests:
    $ref: ./paths/lessons_{lessonId}_tests.yaml

components:
  securitySchemes:
    Oauth2:
      $ref: ../common/components/securitySchemes/Oauth2.yaml

externalDocs:
  url: https://egolia-uit.github.io/egolia
