// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/egolia-uit/egolia/internal/seedcourse"
	"github.com/goforj/wire"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*seedcourse.Seed, func(), error) {
	validate := seedcourse.NewValidate()
	viper := seedcourse.NewViper()
	config, err := seedcourse.NewConfig(validate, viper)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := seedcourse.NewDB(config)
	if err != nil {
		return nil, nil, err
	}
	seed, err := seedcourse.NewSeed(db, config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return seed, func() {
		cleanup()
	}, nil
}

// wire.go:

var ProviderSet = wire.NewSet(seedcourse.ProviderSet)
