## yaml-language-server: $schema=https://www.schemastore.org/openapi-3.X.json
# vim: ft=yaml.openapi
openapi: 3.0.4

servers:
  - url: http://api.egolia.localhost

info:
  description: >
    Egolia API
  version: 0.0.0
  title: Egolia API
  license:
    name: MIT
    url: https://github.com/egolia-uit/egolia/blob/main/LICENSE
  contact:
    name: Egolia Support
    email: egolia@googlegroups.com
  x-apiName: billing

tags:
  - name: Billing
    description: Billing related operations

paths:
  /billing/checkout:
    $ref: ./paths/checkout.yaml
  /billing/admin/analytics/revenue:
    $ref: ./paths/admin_analytics_revenue.yaml
  /billing/transactions:
    $ref: ./paths/transactions.yaml
  /billing/transactions/{transactionId}/complete:
    $ref: ./paths/transactions_{transactionId}_complete.yaml

components:
  securitySchemes:
    Oauth2:
      $ref: ../common/components/securitySchemes/Oauth2.yaml

externalDocs:
  url: https://egolia-uit.github.io/egolia
