## yaml-language-server: $schema=https://www.schemastore.org/openapi-3.X.json
# vim: ft=yaml.openapi
openapi: 3.0.4

servers:
  - url: http://api.egolia.localhost

info:
  description: >
    Egolia API
  version: 0.0.0
  title: Egolia API
  license:
    name: MIT
    url: https://github.com/egolia-uit/egolia/blob/main/LICENSE
  contact:
    name: Egolia Support
    email: egolia@googlegroups.com
  x-apiName: blog

tags:
  - name: Post
    description: Blog post management

paths:
  /blog/posts:
    $ref: ./paths/posts.yaml
  /blog/posts/{postId}:
    $ref: ./paths/posts_{postId}.yaml
  /blog/posts/{postId}/comments:
    $ref: ./paths/posts_{postId}_comments.yaml
  /blog/comments/{commentId}:
    $ref: ./paths/comments_{commentId}.yaml
  /blog/comments/{commentId}/replies:
    $ref: ./paths/comments_{commentId}_replies.yaml

components:
  securitySchemes:
    Oauth2:
      $ref: ../common/components/securitySchemes/Oauth2.yaml

externalDocs:
  url: https://egolia-uit.github.io/egolia
