// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: course.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "github.com/egolia-uit/egolia/pkg/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CourseServiceName is the fully-qualified name of the CourseService service.
	CourseServiceName = "course.CourseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CourseServiceGetCourseTitlesByIdsProcedure is the fully-qualified name of the CourseService's
	// GetCourseTitlesByIds RPC.
	CourseServiceGetCourseTitlesByIdsProcedure = "/course.CourseService/GetCourseTitlesByIds"
	// CourseServiceGetCourseByIdProcedure is the fully-qualified name of the CourseService's
	// GetCourseById RPC.
	CourseServiceGetCourseByIdProcedure = "/course.CourseService/GetCourseById"
)

// CourseServiceClient is a client for the course.CourseService service.
type CourseServiceClient interface {
	GetCourseTitlesByIds(context.Context, *connect.Request[pb.GetCourseTitlesByIdsRequest]) (*connect.Response[pb.GetCourseTitlesByIdsResponse], error)
	GetCourseById(context.Context, *connect.Request[pb.GetCourseByIdRequest]) (*connect.Response[pb.GetCourseByIdResponse], error)
}

// NewCourseServiceClient constructs a client for the course.CourseService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCourseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CourseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	courseServiceMethods := pb.File_course_proto.Services().ByName("CourseService").Methods()
	return &courseServiceClient{
		getCourseTitlesByIds: connect.NewClient[pb.GetCourseTitlesByIdsRequest, pb.GetCourseTitlesByIdsResponse](
			httpClient,
			baseURL+CourseServiceGetCourseTitlesByIdsProcedure,
			connect.WithSchema(courseServiceMethods.ByName("GetCourseTitlesByIds")),
			connect.WithClientOptions(opts...),
		),
		getCourseById: connect.NewClient[pb.GetCourseByIdRequest, pb.GetCourseByIdResponse](
			httpClient,
			baseURL+CourseServiceGetCourseByIdProcedure,
			connect.WithSchema(courseServiceMethods.ByName("GetCourseById")),
			connect.WithClientOptions(opts...),
		),
	}
}

// courseServiceClient implements CourseServiceClient.
type courseServiceClient struct {
	getCourseTitlesByIds *connect.Client[pb.GetCourseTitlesByIdsRequest, pb.GetCourseTitlesByIdsResponse]
	getCourseById        *connect.Client[pb.GetCourseByIdRequest, pb.GetCourseByIdResponse]
}

// GetCourseTitlesByIds calls course.CourseService.GetCourseTitlesByIds.
func (c *courseServiceClient) GetCourseTitlesByIds(ctx context.Context, req *connect.Request[pb.GetCourseTitlesByIdsRequest]) (*connect.Response[pb.GetCourseTitlesByIdsResponse], error) {
	return c.getCourseTitlesByIds.CallUnary(ctx, req)
}

// GetCourseById calls course.CourseService.GetCourseById.
func (c *courseServiceClient) GetCourseById(ctx context.Context, req *connect.Request[pb.GetCourseByIdRequest]) (*connect.Response[pb.GetCourseByIdResponse], error) {
	return c.getCourseById.CallUnary(ctx, req)
}

// CourseServiceHandler is an implementation of the course.CourseService service.
type CourseServiceHandler interface {
	GetCourseTitlesByIds(context.Context, *connect.Request[pb.GetCourseTitlesByIdsRequest]) (*connect.Response[pb.GetCourseTitlesByIdsResponse], error)
	GetCourseById(context.Context, *connect.Request[pb.GetCourseByIdRequest]) (*connect.Response[pb.GetCourseByIdResponse], error)
}

// NewCourseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCourseServiceHandler(svc CourseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	courseServiceMethods := pb.File_course_proto.Services().ByName("CourseService").Methods()
	courseServiceGetCourseTitlesByIdsHandler := connect.NewUnaryHandler(
		CourseServiceGetCourseTitlesByIdsProcedure,
		svc.GetCourseTitlesByIds,
		connect.WithSchema(courseServiceMethods.ByName("GetCourseTitlesByIds")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceGetCourseByIdHandler := connect.NewUnaryHandler(
		CourseServiceGetCourseByIdProcedure,
		svc.GetCourseById,
		connect.WithSchema(courseServiceMethods.ByName("GetCourseById")),
		connect.WithHandlerOptions(opts...),
	)
	return "/course.CourseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CourseServiceGetCourseTitlesByIdsProcedure:
			courseServiceGetCourseTitlesByIdsHandler.ServeHTTP(w, r)
		case CourseServiceGetCourseByIdProcedure:
			courseServiceGetCourseByIdHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCourseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCourseServiceHandler struct{}

func (UnimplementedCourseServiceHandler) GetCourseTitlesByIds(context.Context, *connect.Request[pb.GetCourseTitlesByIdsRequest]) (*connect.Response[pb.GetCourseTitlesByIdsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("course.CourseService.GetCourseTitlesByIds is not implemented"))
}

func (UnimplementedCourseServiceHandler) GetCourseById(context.Context, *connect.Request[pb.GetCourseByIdRequest]) (*connect.Response[pb.GetCourseByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("course.CourseService.GetCourseById is not implemented"))
}
