// Package billing provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package billing

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	OIDCScopes   oIDCContextKey   = "OIDC.Scopes"
	Oauth2Scopes oauth2ContextKey = "Oauth2.Scopes"
)

// Defines values for TransactionStatus.
const (
	Completed TransactionStatus = "completed"
	Failed    TransactionStatus = "failed"
	Pending   TransactionStatus = "pending"
)

// Valid indicates whether the value is a known member of the TransactionStatus enum.
func (e TransactionStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for OrderQuery.
const (
	OrderQueryAsc  OrderQuery = "asc"
	OrderQueryDesc OrderQuery = "desc"
)

// Valid indicates whether the value is a known member of the OrderQuery enum.
func (e OrderQuery) Valid() bool {
	switch e {
	case OrderQueryAsc:
		return true
	case OrderQueryDesc:
		return true
	default:
		return false
	}
}

// Defines values for UnauthorizedErrorType.
const (
	UnauthorizedErrorTypeExtractToken UnauthorizedErrorType = "ExtractToken"
	UnauthorizedErrorTypeFetchJWKS    UnauthorizedErrorType = "FetchJWKS"
	UnauthorizedErrorTypeOPA          UnauthorizedErrorType = "OPA"
	UnauthorizedErrorTypeVerifyToken  UnauthorizedErrorType = "VerifyToken"
)

// Valid indicates whether the value is a known member of the UnauthorizedErrorType enum.
func (e UnauthorizedErrorType) Valid() bool {
	switch e {
	case UnauthorizedErrorTypeExtractToken:
		return true
	case UnauthorizedErrorTypeFetchJWKS:
		return true
	case UnauthorizedErrorTypeOPA:
		return true
	case UnauthorizedErrorTypeVerifyToken:
		return true
	default:
		return false
	}
}

// Defines values for GetPlatformRevenueAnalytics401JSONResponseBodyType.
const (
	GetPlatformRevenueAnalytics401JSONResponseBodyTypeExtractToken GetPlatformRevenueAnalytics401JSONResponseBodyType = "ExtractToken"
	GetPlatformRevenueAnalytics401JSONResponseBodyTypeFetchJWKS    GetPlatformRevenueAnalytics401JSONResponseBodyType = "FetchJWKS"
	GetPlatformRevenueAnalytics401JSONResponseBodyTypeOPA          GetPlatformRevenueAnalytics401JSONResponseBodyType = "OPA"
	GetPlatformRevenueAnalytics401JSONResponseBodyTypeVerifyToken  GetPlatformRevenueAnalytics401JSONResponseBodyType = "VerifyToken"
)

// Valid indicates whether the value is a known member of the GetPlatformRevenueAnalytics401JSONResponseBodyType enum.
func (e GetPlatformRevenueAnalytics401JSONResponseBodyType) Valid() bool {
	switch e {
	case GetPlatformRevenueAnalytics401JSONResponseBodyTypeExtractToken:
		return true
	case GetPlatformRevenueAnalytics401JSONResponseBodyTypeFetchJWKS:
		return true
	case GetPlatformRevenueAnalytics401JSONResponseBodyTypeOPA:
		return true
	case GetPlatformRevenueAnalytics401JSONResponseBodyTypeVerifyToken:
		return true
	default:
		return false
	}
}

// Defines values for CheckoutCourse401JSONResponseBodyType.
const (
	CheckoutCourse401JSONResponseBodyTypeExtractToken CheckoutCourse401JSONResponseBodyType = "ExtractToken"
	CheckoutCourse401JSONResponseBodyTypeFetchJWKS    CheckoutCourse401JSONResponseBodyType = "FetchJWKS"
	CheckoutCourse401JSONResponseBodyTypeOPA          CheckoutCourse401JSONResponseBodyType = "OPA"
	CheckoutCourse401JSONResponseBodyTypeVerifyToken  CheckoutCourse401JSONResponseBodyType = "VerifyToken"
)

// Valid indicates whether the value is a known member of the CheckoutCourse401JSONResponseBodyType enum.
func (e CheckoutCourse401JSONResponseBodyType) Valid() bool {
	switch e {
	case CheckoutCourse401JSONResponseBodyTypeExtractToken:
		return true
	case CheckoutCourse401JSONResponseBodyTypeFetchJWKS:
		return true
	case CheckoutCourse401JSONResponseBodyTypeOPA:
		return true
	case CheckoutCourse401JSONResponseBodyTypeVerifyToken:
		return true
	default:
		return false
	}
}

// Defines values for GetTransactionsParamsOrder.
const (
	GetTransactionsParamsOrderAsc  GetTransactionsParamsOrder = "asc"
	GetTransactionsParamsOrderDesc GetTransactionsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the GetTransactionsParamsOrder enum.
func (e GetTransactionsParamsOrder) Valid() bool {
	switch e {
	case GetTransactionsParamsOrderAsc:
		return true
	case GetTransactionsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for GetTransactions401JSONResponseBodyType.
const (
	GetTransactions401JSONResponseBodyTypeExtractToken GetTransactions401JSONResponseBodyType = "ExtractToken"
	GetTransactions401JSONResponseBodyTypeFetchJWKS    GetTransactions401JSONResponseBodyType = "FetchJWKS"
	GetTransactions401JSONResponseBodyTypeOPA          GetTransactions401JSONResponseBodyType = "OPA"
	GetTransactions401JSONResponseBodyTypeVerifyToken  GetTransactions401JSONResponseBodyType = "VerifyToken"
)

// Valid indicates whether the value is a known member of the GetTransactions401JSONResponseBodyType enum.
func (e GetTransactions401JSONResponseBodyType) Valid() bool {
	switch e {
	case GetTransactions401JSONResponseBodyTypeExtractToken:
		return true
	case GetTransactions401JSONResponseBodyTypeFetchJWKS:
		return true
	case GetTransactions401JSONResponseBodyTypeOPA:
		return true
	case GetTransactions401JSONResponseBodyTypeVerifyToken:
		return true
	default:
		return false
	}
}

// Defines values for CompleteTransaction401JSONResponseBodyType.
const (
	ExtractToken CompleteTransaction401JSONResponseBodyType = "ExtractToken"
	FetchJWKS    CompleteTransaction401JSONResponseBodyType = "FetchJWKS"
	OPA          CompleteTransaction401JSONResponseBodyType = "OPA"
	VerifyToken  CompleteTransaction401JSONResponseBodyType = "VerifyToken"
)

// Valid indicates whether the value is a known member of the CompleteTransaction401JSONResponseBodyType enum.
func (e CompleteTransaction401JSONResponseBodyType) Valid() bool {
	switch e {
	case ExtractToken:
		return true
	case FetchJWKS:
		return true
	case OPA:
		return true
	case VerifyToken:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Message Human-readable error message
	Message string `json:"message"`

	// MoreInfo URL with more information about the error
	MoreInfo *string `json:"more_info,omitempty"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// HasNext Whether there is a next page
	HasNext bool `json:"hasNext"`

	// HasPrev Whether there is a previous page
	HasPrev bool `json:"hasPrev"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Page Current page number
	Page int `json:"page"`

	// Total Total number of items
	Total int `json:"total"`

	// TotalPages Total number of pages
	TotalPages int `json:"totalPages"`
}

// RevenueAnalytics defines model for RevenueAnalytics.
type RevenueAnalytics struct {
	CompletedTransactions int       `json:"completedTransactions"`
	FailedTransactions    int       `json:"failedTransactions"`
	From                  time.Time `json:"from"`
	To                    time.Time `json:"to"`
	TotalRevenue          int64     `json:"totalRevenue"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Amount      *int64              `json:"amount,omitempty"`
	CourseId    openapi_types.UUID  `json:"courseId"`
	CourseTitle *Title              `json:"courseTitle,omitempty"`
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// Status Current status of a billing transaction
	Status TransactionStatus `json:"status"`

	// UserEmail Email from Authentik
	UserEmail *Email `json:"userEmail"`

	// UserId User ID from Authentik (need to change subject mode to User's ID instead of hashed)
	UserId Id `json:"userId"`

	// Username Username from Authentik
	Username Username `json:"username"`
}

// TransactionStatus Current status of a billing transaction
type TransactionStatus string

// Email Email from Authentik
type Email = openapi_types.Email

// Id User ID from Authentik (need to change subject mode to User's ID instead of hashed)
type Id = string

// Title defines model for title.
type Title = string

// Username Username from Authentik
type Username = string

// LimitQuery defines model for limitQuery.
type LimitQuery = int

// OrderQuery defines model for orderQuery.
type OrderQuery string

// PageQuery defines model for pageQuery.
type PageQuery = int

// TransactionIdPath defines model for transactionIdPath.
type TransactionIdPath = openapi_types.UUID

// BadRequestError defines model for BadRequestError.
type BadRequestError = Error

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// UnauthorizedError The error response body returned when JWT validation or OPA authorization fails.
type UnauthorizedError struct {
	// CustomMessage An optional, developer-defined message, often populated by OPA policy violations.
	CustomMessage *string `json:"custom_message"`

	// Details A descriptive message providing technical context for the failure.
	Details string `json:"details"`

	// Type The category of the error encountered during the middleware lifecycle.
	Type UnauthorizedErrorType `json:"type"`
}

// UnauthorizedErrorType The category of the error encountered during the middleware lifecycle.
type UnauthorizedErrorType string

// oIDCContextKey is the context key for OIDC security scheme
type oIDCContextKey string

// oauth2ContextKey is the context key for Oauth2 security scheme
type oauth2ContextKey string

// GetPlatformRevenueAnalyticsParams defines parameters for GetPlatformRevenueAnalytics.
type GetPlatformRevenueAnalyticsParams struct {
	From openapi_types.Date `form:"from" json:"from"`
	To   openapi_types.Date `form:"to" json:"to"`
}

// GetPlatformRevenueAnalytics401JSONResponseBodyType defines parameters for GetPlatformRevenueAnalytics.
type GetPlatformRevenueAnalytics401JSONResponseBodyType string

// CheckoutCourse401JSONResponseBodyType defines parameters for CheckoutCourse.
type CheckoutCourse401JSONResponseBodyType string

// GetTransactionsParams defines parameters for GetTransactions.
type GetTransactionsParams struct {
	// Page Page number for pagination
	Page *PageQuery `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`

	// Order Sort order
	Order    *GetTransactionsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	CourseId *openapi_types.UUID         `form:"courseId,omitempty" json:"courseId,omitempty"`

	// LearnerId If requested by non admin, then it will be that user
	LearnerId *Id `form:"learnerId,omitempty" json:"learnerId,omitempty"`
}

// GetTransactionsParamsOrder defines parameters for GetTransactions.
type GetTransactionsParamsOrder string

// GetTransactions401JSONResponseBodyType defines parameters for GetTransactions.
type GetTransactions401JSONResponseBodyType string

// CompleteTransaction401JSONResponseBodyType defines parameters for CompleteTransaction.
type CompleteTransaction401JSONResponseBodyType string

// CheckoutCourseJSONRequestBody defines body for CheckoutCourse for application/json ContentType.
type CheckoutCourseJSONRequestBody = Transaction
