// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommentRepo creates a new instance of MockCommentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentRepo {
	mock := &MockCommentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommentRepo is an autogenerated mock type for the CommentRepo type
type MockCommentRepo struct {
	mock.Mock
}

type MockCommentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentRepo) EXPECT() *MockCommentRepo_Expecter {
	return &MockCommentRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockCommentRepo
func (_mock *MockCommentRepo) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommentRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCommentRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCommentRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockCommentRepo_Delete_Call {
	return &MockCommentRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCommentRepo_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCommentRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepo_Delete_Call) Return(err error) *MockCommentRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommentRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockCommentRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByPostID provides a mock function for the type MockCommentRepo
func (_mock *MockCommentRepo) DeleteByPostID(ctx context.Context, postID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPostID")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepo_DeleteByPostID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByPostID'
type MockCommentRepo_DeleteByPostID_Call struct {
	*mock.Call
}

// DeleteByPostID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uuid.UUID
func (_e *MockCommentRepo_Expecter) DeleteByPostID(ctx interface{}, postID interface{}) *MockCommentRepo_DeleteByPostID_Call {
	return &MockCommentRepo_DeleteByPostID_Call{Call: _e.mock.On("DeleteByPostID", ctx, postID)}
}

func (_c *MockCommentRepo_DeleteByPostID_Call) Run(run func(ctx context.Context, postID uuid.UUID)) *MockCommentRepo_DeleteByPostID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepo_DeleteByPostID_Call) Return(n int, err error) *MockCommentRepo_DeleteByPostID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCommentRepo_DeleteByPostID_Call) RunAndReturn(run func(ctx context.Context, postID uuid.UUID) (int, error)) *MockCommentRepo_DeleteByPostID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReplies provides a mock function for the type MockCommentRepo
func (_mock *MockCommentRepo) DeleteReplies(ctx context.Context, commentID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReplies")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepo_DeleteReplies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReplies'
type MockCommentRepo_DeleteReplies_Call struct {
	*mock.Call
}

// DeleteReplies is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
func (_e *MockCommentRepo_Expecter) DeleteReplies(ctx interface{}, commentID interface{}) *MockCommentRepo_DeleteReplies_Call {
	return &MockCommentRepo_DeleteReplies_Call{Call: _e.mock.On("DeleteReplies", ctx, commentID)}
}

func (_c *MockCommentRepo_DeleteReplies_Call) Run(run func(ctx context.Context, commentID uuid.UUID)) *MockCommentRepo_DeleteReplies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepo_DeleteReplies_Call) Return(n int, err error) *MockCommentRepo_DeleteReplies_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCommentRepo_DeleteReplies_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID) (int, error)) *MockCommentRepo_DeleteReplies_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCommentRepo
func (_mock *MockCommentRepo) Get(ctx context.Context, id uuid.UUID) (*Comment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Comment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Comment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCommentRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCommentRepo_Expecter) Get(ctx interface{}, id interface{}) *MockCommentRepo_Get_Call {
	return &MockCommentRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockCommentRepo_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCommentRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepo_Get_Call) Return(comment *Comment, err error) *MockCommentRepo_Get_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockCommentRepo_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*Comment, error)) *MockCommentRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockCommentRepo
func (_mock *MockCommentRepo) Save(ctx context.Context, comment *Comment) error {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Comment) error); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommentRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockCommentRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - comment *Comment
func (_e *MockCommentRepo_Expecter) Save(ctx interface{}, comment interface{}) *MockCommentRepo_Save_Call {
	return &MockCommentRepo_Save_Call{Call: _e.mock.On("Save", ctx, comment)}
}

func (_c *MockCommentRepo_Save_Call) Run(run func(ctx context.Context, comment *Comment)) *MockCommentRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Comment
		if args[1] != nil {
			arg1 = args[1].(*Comment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepo_Save_Call) Return(err error) *MockCommentRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommentRepo_Save_Call) RunAndReturn(run func(ctx context.Context, comment *Comment) error) *MockCommentRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostRepo creates a new instance of MockPostRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostRepo {
	mock := &MockPostRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostRepo is an autogenerated mock type for the PostRepo type
type MockPostRepo struct {
	mock.Mock
}

type MockPostRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostRepo) EXPECT() *MockPostRepo_Expecter {
	return &MockPostRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockPostRepo
func (_mock *MockPostRepo) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPostRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPostRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockPostRepo_Delete_Call {
	return &MockPostRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPostRepo_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPostRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepo_Delete_Call) Return(err error) *MockPostRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockPostRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockPostRepo
func (_mock *MockPostRepo) Get(ctx context.Context, id uuid.UUID) (*Post, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Post, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Post); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPostRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPostRepo_Expecter) Get(ctx interface{}, id interface{}) *MockPostRepo_Get_Call {
	return &MockPostRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockPostRepo_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPostRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepo_Get_Call) Return(post *Post, err error) *MockPostRepo_Get_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostRepo_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*Post, error)) *MockPostRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockPostRepo
func (_mock *MockPostRepo) Save(ctx context.Context, post *Post) error {
	ret := _mock.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Post) error); ok {
		r0 = returnFunc(ctx, post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockPostRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - post *Post
func (_e *MockPostRepo_Expecter) Save(ctx interface{}, post interface{}) *MockPostRepo_Save_Call {
	return &MockPostRepo_Save_Call{Call: _e.mock.On("Save", ctx, post)}
}

func (_c *MockPostRepo_Save_Call) Run(run func(ctx context.Context, post *Post)) *MockPostRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Post
		if args[1] != nil {
			arg1 = args[1].(*Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepo_Save_Call) Return(err error) *MockPostRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepo_Save_Call) RunAndReturn(run func(ctx context.Context, post *Post) error) *MockPostRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepoRegistry creates a new instance of MockRepoRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoRegistry {
	mock := &MockRepoRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepoRegistry is an autogenerated mock type for the RepoRegistry type
type MockRepoRegistry struct {
	mock.Mock
}

type MockRepoRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoRegistry) EXPECT() *MockRepoRegistry_Expecter {
	return &MockRepoRegistry_Expecter{mock: &_m.Mock}
}

// Comment provides a mock function for the type MockRepoRegistry
func (_mock *MockRepoRegistry) Comment() CommentRepo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Comment")
	}

	var r0 CommentRepo
	if returnFunc, ok := ret.Get(0).(func() CommentRepo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CommentRepo)
		}
	}
	return r0
}

// MockRepoRegistry_Comment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Comment'
type MockRepoRegistry_Comment_Call struct {
	*mock.Call
}

// Comment is a helper method to define mock.On call
func (_e *MockRepoRegistry_Expecter) Comment() *MockRepoRegistry_Comment_Call {
	return &MockRepoRegistry_Comment_Call{Call: _e.mock.On("Comment")}
}

func (_c *MockRepoRegistry_Comment_Call) Run(run func()) *MockRepoRegistry_Comment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepoRegistry_Comment_Call) Return(commentRepo CommentRepo) *MockRepoRegistry_Comment_Call {
	_c.Call.Return(commentRepo)
	return _c
}

func (_c *MockRepoRegistry_Comment_Call) RunAndReturn(run func() CommentRepo) *MockRepoRegistry_Comment_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function for the type MockRepoRegistry
func (_mock *MockRepoRegistry) Post() PostRepo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 PostRepo
	if returnFunc, ok := ret.Get(0).(func() PostRepo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PostRepo)
		}
	}
	return r0
}

// MockRepoRegistry_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockRepoRegistry_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
func (_e *MockRepoRegistry_Expecter) Post() *MockRepoRegistry_Post_Call {
	return &MockRepoRegistry_Post_Call{Call: _e.mock.On("Post")}
}

func (_c *MockRepoRegistry_Post_Call) Run(run func()) *MockRepoRegistry_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepoRegistry_Post_Call) Return(postRepo PostRepo) *MockRepoRegistry_Post_Call {
	_c.Call.Return(postRepo)
	return _c
}

func (_c *MockRepoRegistry_Post_Call) RunAndReturn(run func() PostRepo) *MockRepoRegistry_Post_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Execute(ctx context.Context, fn func(repoRegistry RepoRegistry) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(repoRegistry RepoRegistry) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUnitOfWork_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(repoRegistry RepoRegistry) error
func (_e *MockUnitOfWork_Expecter) Execute(ctx interface{}, fn interface{}) *MockUnitOfWork_Execute_Call {
	return &MockUnitOfWork_Execute_Call{Call: _e.mock.On("Execute", ctx, fn)}
}

func (_c *MockUnitOfWork_Execute_Call) Run(run func(ctx context.Context, fn func(repoRegistry RepoRegistry) error)) *MockUnitOfWork_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(repoRegistry RepoRegistry) error
		if args[1] != nil {
			arg1 = args[1].(func(repoRegistry RepoRegistry) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Execute_Call) Return(err error) *MockUnitOfWork_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Execute_Call) RunAndReturn(run func(ctx context.Context, fn func(repoRegistry RepoRegistry) error) error) *MockUnitOfWork_Execute_Call {
	_c.Call.Return(run)
	return _c
}
